package liangwenhan.web.dao;

import java.util.List;
import java.util.Map;

import liangwenhan.web.entity.Ability;

public interface AbilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insert(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insertSelective(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    Ability selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKeySelective(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKey(Ability record);
    
    /**
     * userId
     * pageSize
     * pageBegin
     * @param queryMap
     * @return
     */
    List<Ability> selectAbilityListByUserId(Map<String, Object> queryMap);
}