package liangwenhan.web.dao;

import liangwenhan.web.entity.ActionConsequence;

public interface ActionConsequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insert(ActionConsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insertSelective(ActionConsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    ActionConsequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKeySelective(ActionConsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_consequence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKey(ActionConsequence record);
}