package liangwenhan.web.dao;

import liangwenhan.web.entity.Action;

public interface ActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    Action selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    int updateByPrimaryKey(Action record);
}