package liangwenhan.web.entity;

public class Ability {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.point
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.id
     *
     * @return the value of ability.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.id
     *
     * @param id the value for ability.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.userId
     *
     * @return the value of ability.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.userId
     *
     * @param userid the value for ability.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.name
     *
     * @return the value of ability.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.name
     *
     * @param name the value for ability.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.description
     *
     * @return the value of ability.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.description
     *
     * @param description the value for ability.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.point
     *
     * @return the value of ability.point
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.point
     *
     * @param point the value for ability.point
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}