package liangwenhan.web.entity;

public class Action {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.unit
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.last
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer last;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.id
     *
     * @return the value of action.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.id
     *
     * @param id the value for action.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.userId
     *
     * @return the value of action.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.userId
     *
     * @param userid the value for action.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.unit
     *
     * @return the value of action.unit
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.unit
     *
     * @param unit the value for action.unit
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.name
     *
     * @return the value of action.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.name
     *
     * @param name the value for action.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.description
     *
     * @return the value of action.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.description
     *
     * @param description the value for action.description
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.last
     *
     * @return the value of action.last
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.last
     *
     * @param last the value for action.last
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setLast(Integer last) {
        this.last = last;
    }
}