package liangwenhan.web.entity;

import java.util.Date;

public class ActionTransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer actionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.beginTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.endTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_transaction.unit_count
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer unitCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.id
     *
     * @return the value of action_transaction.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.id
     *
     * @param id the value for action_transaction.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.userId
     *
     * @return the value of action_transaction.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.userId
     *
     * @param userid the value for action_transaction.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.actionId
     *
     * @return the value of action_transaction.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.actionId
     *
     * @param actionid the value for action_transaction.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setActionid(Integer actionid) {
        this.actionid = actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.beginTime
     *
     * @return the value of action_transaction.beginTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.beginTime
     *
     * @param begintime the value for action_transaction.beginTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.endTime
     *
     * @return the value of action_transaction.endTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.endTime
     *
     * @param endtime the value for action_transaction.endTime
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_transaction.unit_count
     *
     * @return the value of action_transaction.unit_count
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getUnitCount() {
        return unitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_transaction.unit_count
     *
     * @param unitCount the value for action_transaction.unit_count
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUnitCount(Integer unitCount) {
        this.unitCount = unitCount;
    }
}