package liangwenhan.web.entity;

public class ActionConsequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String actionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.result
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.type
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.effectAttributeFields
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String effectattributefields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_consequence.effectAbilityId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer effectabilityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.id
     *
     * @return the value of action_consequence.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.id
     *
     * @param id the value for action_consequence.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.userId
     *
     * @return the value of action_consequence.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.userId
     *
     * @param userid the value for action_consequence.userId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.actionId
     *
     * @return the value of action_consequence.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.actionId
     *
     * @param actionid the value for action_consequence.actionId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setActionid(String actionid) {
        this.actionid = actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.result
     *
     * @return the value of action_consequence.result
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.result
     *
     * @param result the value for action_consequence.result
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.type
     *
     * @return the value of action_consequence.type
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.type
     *
     * @param type the value for action_consequence.type
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.effectAttributeFields
     *
     * @return the value of action_consequence.effectAttributeFields
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getEffectattributefields() {
        return effectattributefields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.effectAttributeFields
     *
     * @param effectattributefields the value for action_consequence.effectAttributeFields
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setEffectattributefields(String effectattributefields) {
        this.effectattributefields = effectattributefields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_consequence.effectAbilityId
     *
     * @return the value of action_consequence.effectAbilityId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getEffectabilityid() {
        return effectabilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_consequence.effectAbilityId
     *
     * @param effectabilityid the value for action_consequence.effectAbilityId
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setEffectabilityid(Integer effectabilityid) {
        this.effectabilityid = effectabilityid;
    }
}