package liangwenhan.web.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.strength
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer strength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.will
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer will;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hp
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer hp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.horizon
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer horizon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.intelligence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer intelligence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.logic
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    private Integer logic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.strength
     *
     * @return the value of user.strength
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getStrength() {
        return strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.strength
     *
     * @param strength the value for user.strength
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setStrength(Integer strength) {
        this.strength = strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.will
     *
     * @return the value of user.will
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getWill() {
        return will;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.will
     *
     * @param will the value for user.will
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setWill(Integer will) {
        this.will = will;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hp
     *
     * @return the value of user.hp
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hp
     *
     * @param hp the value for user.hp
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setHp(Integer hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.horizon
     *
     * @return the value of user.horizon
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getHorizon() {
        return horizon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.horizon
     *
     * @param horizon the value for user.horizon
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setHorizon(Integer horizon) {
        this.horizon = horizon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.intelligence
     *
     * @return the value of user.intelligence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getIntelligence() {
        return intelligence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.intelligence
     *
     * @param intelligence the value for user.intelligence
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setIntelligence(Integer intelligence) {
        this.intelligence = intelligence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.logic
     *
     * @return the value of user.logic
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public Integer getLogic() {
        return logic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.logic
     *
     * @param logic the value for user.logic
     *
     * @mbg.generated Sun Aug 06 19:33:53 CST 2017
     */
    public void setLogic(Integer logic) {
        this.logic = logic;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", account=" + account + ", password=" + password + ", name=" + name + ", age=" + age
				+ ", sex=" + sex + ", strength=" + strength + ", will=" + will + ", hp=" + hp + ", horizon=" + horizon
				+ ", intelligence=" + intelligence + ", logic=" + logic + "]";
	}
    
    
}